/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wooapp;

import org.junit.jupiter.api.Test;

class ClientAppTest {
    @Test void appHasAGreeting() {
        ClientApp classUnderTest = new ClientApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
