/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wooapp;

import org.junit.jupiter.api.Test;

class ServerAppTest {
    @Test void appHasAGreeting() {
        ServerApp classUnderTest = new ServerApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
